title: Hansol Kim | CV
description: CV of Hansol Kim, Ph.D. Candidate in Industrial & Management Engineering at POSTECH.
url: https://hskim-kr.github.io
baseurl: '/hansol-cv'
theme_skin: blue

sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-minifier

exclude:
  - docker-compose.yml
